/**
 *
 * {@link ClassText}.java
 *
 * @author Jens Ebert
 *
 * @date 04.05.2020
 *
 */
package com.github.j2a.springbootto.generators;

/**
 * {@link ClassText}
 *
 */
public class ClassText {
	public static final String GAME_RELEASE = "/**\n" + " *\n" + " * {@link Game}.java\n" + " *\n"
		+ " * @author Jens Ebert\n" + " *\n" + " * @date 27.04.2019\n" + " *\n" + " */\n"
		+ "package org.mycollection.games.server.games.impl.data;\n" + "\n" + "import java.util.HashSet;\n"
		+ "import java.util.Set;\n" + "\n" + "import javax.persistence.CascadeType;\n"
		+ "import javax.persistence.Column;\n" + "import javax.persistence.Entity;\n"
		+ "import javax.persistence.EnumType;\n" + "import javax.persistence.Enumerated;\n"
		+ "import javax.persistence.FetchType;\n" + "import javax.persistence.JoinColumn;\n"
		+ "import javax.persistence.ManyToOne;\n" + "import javax.persistence.OneToMany;\n"
		+ "import javax.persistence.Table;\n" + "import javax.validation.constraints.NotNull;\n" + "\n"
		+ "import org.mycollection.games.server.games.api.GameReleaseTO;\n"
		+ "import org.mycollection.games.server.games.api.Packaging;\n"
		+ "import org.mycollection.games.server.games.api.VideoFormat;\n"
		+ "import org.mycollection.games.server.utils.AbstractEntity;\n" + "\n" + "/**\n" + " * {@link GameReleaseTO}\n"
		+ " *\n" + " */\n" + "@Entity\n" + "@Table(name = \"game_release\")\n"
		+ "public class GameRelease extends AbstractEntity {\n" + "\n" + "	@ManyToOne\n"
		+ "	@JoinColumn(referencedColumnName = \"id\", name = \"game_id\")\n" + "	private Game game;\n" + "\n"
		+ "	@Column(name = \"title\")\n" + "	private String title;\n" + "\n" + "	@Column(name = \"description\")\n"
		+ "	private String description;\n" + "\n" + "	@Column(name = \"region_id\")\n"
		+ "	private String regionId;\n" + "\n" + "	@Enumerated(EnumType.STRING)\n"
		+ "	@Column(name = \"video_format\")\n" + "	private VideoFormat videoFormat;\n" + "\n"
		+ "	@Column(name = \"publisher_id\")\n" + "	private String publisherId;\n" + "\n"
		+ "	@Column(name = \"developer_id\")\n" + "	private String developerId;\n" + "\n"
		+ "	@Column(name = \"barcode\")\n" + "	private String barcode;\n" + "\n"
		+ "	@Column(name = \"publish_date\")\n" + "	private String publishDate;\n" + "\n"
		+ "	@Enumerated(EnumType.STRING)\n" + "	@Column(name = \"packaging\")\n" + "	private Packaging packaging;\n"
		+ "\n" + "	@Column(name = \"media_type\")\n" + "	private String mediaType;\n" + "\n"
		+ "	@Column(name = \"rating\")\n" + "	private String rating;\n" + "\n"
		+ "	@Column(name = \"distinctive_feature\")\n" + "	private String distinctiveFeature;\n" + "\n"
		+ "	@OneToMany(fetch = FetchType.LAZY, mappedBy = \"gameRelease\", cascade = { CascadeType.PERSIST })\n"
		+ "	private Set<GameReleaseImage> gameReleaseImages;\n" + "\n" + "	@Column(name = \"edition\")\n"
		+ "	private String edition;\n" + "\n" + "	@ManyToOne(cascade = CascadeType.PERSIST)\n"
		+ "	@JoinColumn(referencedColumnName = \"id\", name = \"platform_id\")\n" + "	private Platform platform;\n"
		+ "\n" + "	@Column(name = \"cover_image_link\")\n" + "	private String coverImageLink;\n" + "\n"
		+ "	@Column(name = \"cover_image_thumb_link\")\n" + "	private String coverImageThumbLink;\n" + "\n"
		+ "	@Column(name = \"players_min\")\n" + "	private Integer playersMin;\n" + "\n"
		+ "	@Column(name = \"players_max\")\n" + "	private Integer playersMax;\n" + "\n"
		+ "	public void addGameReleaseImage(@NotNull GameReleaseImage image) {\n"
		+ "		if (gameReleaseImages == null) {\n" + "			gameReleaseImages = new HashSet<>();\n" + "		}\n"
		+ "\n" + "		gameReleaseImages.add(image);\n" + "	}\n" + "\n" + "	public String getBarcode() {\n"
		+ "		return barcode;\n" + "	}\n" + "\n" + "	public String getCoverImageLink() {\n"
		+ "		return coverImageLink;\n" + "	}\n" + "\n" + "	public String getCoverImageThumbLink() {\n"
		+ "		return coverImageThumbLink;\n" + "	}\n" + "\n" + "	public String getDescription() {\n"
		+ "		return description;\n" + "	}\n" + "\n" + "	public String getDeveloperId() {\n"
		+ "		return developerId;\n" + "	}\n" + "\n" + "	public String getDistinctiveFeature() {\n"
		+ "		return distinctiveFeature;\n" + "	}\n" + "\n" + "	public String getEdition() {\n"
		+ "		return edition;\n" + "	}\n" + "\n" + "	public Game getGame() {\n" + "		return game;\n" + "	}\n"
		+ "\n" + "	public Set<GameReleaseImage> getGameReleaseImages() {\n" + "		return gameReleaseImages;\n"
		+ "	}\n" + "\n" + "	public String getMediaType() {\n" + "		return mediaType;\n" + "	}\n" + "\n"
		+ "	public Packaging getPackaging() {\n" + "		return packaging;\n" + "	}\n" + "\n"
		+ "	public Platform getPlatform() {\n" + "		return platform;\n" + "	}\n" + "\n"
		+ "	public Integer getPlayersMax() {\n" + "		return playersMax;\n" + "	}\n" + "\n"
		+ "	public Integer getPlayersMin() {\n" + "		return playersMin;\n" + "	}\n" + "\n"
		+ "	public String getPublishDate() {\n" + "		return publishDate;\n" + "	}\n" + "\n"
		+ "	public String getPublisherId() {\n" + "		return publisherId;\n" + "	}\n" + "\n"
		+ "	public String getRating() {\n" + "		return rating;\n" + "	}\n" + "\n"
		+ "	public String getRegionId() {\n" + "		return regionId;\n" + "	}\n" + "\n"
		+ "	public String getTitle() {\n" + "		return title;\n" + "	}\n" + "\n"
		+ "	public VideoFormat getVideoFormat() {\n" + "		return videoFormat;\n" + "	}\n" + "\n"
		+ "	public void setBarcode(String letsPlayLink) {\n" + "		barcode = letsPlayLink;\n" + "	}\n" + "\n"
		+ "	public void setCoverImageLink(String coverImageLink) {\n" + "		this.coverImageLink = coverImageLink;\n"
		+ "	}\n" + "\n" + "	public void setCoverImageThumbLink(String coverImageThumbLink) {\n"
		+ "		this.coverImageThumbLink = coverImageThumbLink;\n" + "	}\n" + "\n"
		+ "	public void setDescription(String description) {\n" + "		this.description = description;\n" + "	}\n"
		+ "\n" + "	public void setDeveloperId(String reviewLink) {\n" + "		developerId = reviewLink;\n" + "	}\n"
		+ "\n" + "	public void setDistinctiveFeature(String distinctiveFeature) {\n"
		+ "		this.distinctiveFeature = distinctiveFeature;\n" + "	}\n" + "\n"
		+ "	public void setEdition(String edition) {\n" + "		this.edition = edition;\n" + "	}\n" + "\n"
		+ "	public void setGame(Game game) {\n" + "		this.game = game;\n" + "	}\n" + "\n"
		+ "	public void setGameReleaseImages(Set<GameReleaseImage> gameReleaseImages) {\n"
		+ "		this.gameReleaseImages = gameReleaseImages;\n" + "	}\n" + "\n"
		+ "	public void setMediaType(String mediaType) {\n" + "		this.mediaType = mediaType;\n" + "	}\n" + "\n"
		+ "	public void setPackaging(Packaging packaging) {\n" + "		this.packaging = packaging;\n" + "	}\n" + "\n"
		+ "	public void setPlatform(Platform platform) {\n" + "		this.platform = platform;\n" + "	}\n" + "\n"
		+ "	public void setPlayersMax(Integer playersMax) {\n" + "		this.playersMax = playersMax;\n" + "	}\n"
		+ "\n" + "	public void setPlayersMin(Integer playersMin) {\n" + "		this.playersMin = playersMin;\n"
		+ "	}\n" + "\n" + "	public void setPublishDate(String publishDate) {\n"
		+ "		this.publishDate = publishDate;\n" + "	}\n" + "\n"
		+ "	public void setPublisherId(String sourceDBGameId) {\n" + "		publisherId = sourceDBGameId;\n" + "	}\n"
		+ "\n" + "	public void setRating(String rating) {\n" + "		this.rating = rating;\n" + "	}\n" + "\n"
		+ "	public void setRegionId(String regionId) {\n" + "		this.regionId = regionId;\n" + "	}\n" + "\n"
		+ "	public void setTitle(String title) {\n" + "		this.title = title;\n" + "	}\n" + "\n"
		+ "	public void setVideoFormat(VideoFormat videoFormat) {\n" + "		this.videoFormat = videoFormat;\n"
		+ "	}\n" + "}\n" + "";
}
